---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.windows
    version: 1.11.1
  - name: awx.awx
    version: 21.7.0
  - name: chocolatey.chocolatey
    version: 1.3.1
  - name: community.general
    version: 5.6.0
  - name: community.vmware
    version: 2.10.0
  - name: community.windows