---
# Open holes in the firewall

- name: Open holes in the Windows firewall
  hosts: all
  gather_facts: no
  become_method: runas

  tasks:
    - name: Open ICMP
      community.windows.win_firewall_rule:
        name: ICMP Allow incoming V4 echo request
        enabled: yes
        state: present
        action: allow
        direction: in
        protocol: icmpv4
        icmp_type_code:
        - '8:*'
