---
## Prepares a Red Hat 8 server for Ansible

- name: Install EPEL Repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: Install PIP for Python3
  yum:
    name: python3-pip
    state: present

- name: Make sure pexpect is removed from distribution
  yum:
    name: pexpect
    state: absent

- name: Install pexpect using pip
  pip:
    name: pexpect

- name: Install Chrony to sync time
  yum:
    name:
      - chrony
    state: present

- name: Change Default Admin Password
  ansible.builtin.user:
    name: root
    password: "{{ admin_pass | password_hash('sha512') }}"
