---
- name: check if reboot is needed
  shell: needs-restarting | wc -l
  register: needs_restarting
  changed_when: needs_restarting.stdout|int != 0

- name: reboot host if needed
  block: 
  
  - name: Get needs_restarting output
    shell: needs-restarting
    register: nr_output

  - name: Send out Reboot Email
    become: false
    mail:
      host: "{{ mail_server }}"
      port: "{{ mail_port }}"
      from: "{{ from_email }}"
      to: "{{ notify_email }}"
      subject: ANSIBLE - Rebooting {{ ansible_hostname }}
      body: |
        System {{ ansible_hostname }} needs to be rebooted after patching.
  
        Here is the output from the "needs_restarting" command:

        {{ nr_output.stdout }}  
    delegate_to: localhost

  - name: Reboot host and wait for host to return
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 60
      test_command: whoami

  - name: check if host has booted within last 300 sec
    shell: test $(cat /proc/uptime | cut -d. -f1) -lt 300
    changed_when: false
    register: reboot_check

  - name: alert if host has not been rebooted
    fail:
      msg: "{{ ansible_host }} has not booted, manual check needed"
    when: reboot_check.rc != 0
  when: needs_restarting.stdout|int != 0
