---
- name: Take Snapshot of VMware Guest
  hosts: localhost
  gather_facts: False

- name: Get date for Snapshot Name
  debug:
    var: ansible_date_time

  vars:
    snapshot_name: "Ansible - Patching - {{ ansible_date_time.date }}"

  tasks:
    - name: Take Snapshot (vCenter)
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        folder: "/"
        name: "{{ vm_guest_name }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
      delegate_to: localhost
