---

- name: Create user account (aur_builder)
  ansible.builtin.user:
    name: aur_builder
  become: true

- name: Modify Sudo to allow Pacman for aur_builder
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    validate: /usr/sbin/visudo -cf %s
    mode: '0600'
    owner: root
    group: root
    create: true
  become: true
