---
- name: Prepare localhost for Ansible usage
  hosts: all
  gather_facts: yes

  tasks:

- name: Prepare host(s) for Ansible usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Set authorized key on remote
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
