---
# Configures RHEL7 for standards

- name: Enable FastestMirror YUM Plugin
  lineinfile:
    path: /etc/yum.conf
    line: FastestMirror=True

- name: Remove Packages - sendmail
  yum:
    name:
      - sendmail
    state: absent

- name: Install Packages - postfix, net-snmp, ca-certificates, gdb
  yum:
    name: 
      - postfix
      - net-snmp
      - ca-certificates
      - gdb
    state: present

- name: Disable IPv6
  copy:
    src: "{{ role_path }}/files/99-ipv6.conf"
    dest: /etc/sysctl.d
    owner: root
    group: root
    mode: 0644

- name: Set timezone to America/Edmonton
  community.general.timezone:
    name: America/Edmonton
