---
# Configures Ubuntu 22 for standards

- name: Remove Unnecessary Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - sendmail

- name: Install Necessary Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - postfix
    - snmpd
    - chrony
    - ca-certificates
    - gdb
    - btop
    - htop
    - net-tools

- name: Disable IPv6
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-ipv6.conf"
    dest: /etc/sysctl.d
    owner: root
    group: root
    mode: 0644

- name: Allow SSH Through Firewall (UFW)
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
    
- name: Turn on Firewall (UFW)
  community.general.ufw:
    state: enabled
    default: deny

- name: Set timezone to America/Edmonton
  community.general.timezone:
    name: America/Edmonton
